### ISSUE TITLE
LICENSE for the code?

### ISSUE THREAD

**Issue by silentyak** [bansalsurya/whiteboard-app#1]
Hello!
What is your license for the code? I searched the repo, the code does not appear to have a license. 

Most people use the MIT license. See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository for guidance in choosing your license, if you want to add a license (which helps devs in actually using your code).

Thank you!

**Comment by silentyak** [comment]
Here's an easy way to add a license to your repo:
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by bansalsurya** [comment]
Hey @silentyak thank you for raising the issue. Added the appropriate license.
